### ISSUE TITLE
User docs styles request

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern-com-website#260]
I have no assigning rights in this repo, but this is directed @philwareham.

I'm requesting a few, relatively simple, styles additions to the brand's CSS for use in user docs (and wherever other platform might find useful). I recommend you have a look at the associated sections in the new user docs guidelines, beginning at [Markup and styling](https://docs.textpattern.com/brand/user-docs-guide#markup-and-styling), as it will explain in what context these are needed.

The code below is a humble start at getting it done, but by all means tweak as needed. If you change the selectors names, however, let me know, because that impacts user docs, as well docs guidelines. I can then edit accordingly.

First, here are two that quietly do their good thing after inclusion, with no further ado from anyone....

### Reference-mark notes in Tables DONE
See [Notes in tables](https://docs.textpattern.com/brand/user-docs-guide#notes-in-tables) and [Tables](https://docs.textpattern.com/brand/user-docs-guide#tables).

```css
tfoot ol {
	list-style-type:none;
	text-indent:-.75em;
	padding-left:.75em;	
}

tfoot li {margin:.15em 0;}

ol.refmarks {
	list-style-type:none;
	text-indent:-.75em;
	padding-left:.75em;	
}

.refmarks li::before {margin-right:.4em;}

.refmarks li:first-child:before {content:'\002a';} /* asterisk */
.refmarks li:nth-of-type(2):before {content:'\2020';} /* dagger */
.refmarks li:nth-of-type(3):before {content:'\2021';} /* double dagger */
.refmarks li:nth-of-type(4):before {content:'\00a7';} /* section */
.refmarks li:nth-of-type(5):before {content:'\00b6';} /* pilcrow */
.refmarks li:nth-of-type(6):before {content:'\2016';} /* parallel bars */

/*Should we want to provide for another six notes (notes 7 through 12), 
they would continue like this, as double entities...
.refmarks li:nth-of-type(7):before {content:'\002a\002a';}
*/
```

### Faux header in endnotes container DONE

See last para in [Notes in main text](https://docs.textpattern.com/brand/user-docs-guide#notes-in-main-text). But, basically, since we can't add a header element in the Kramdown generating the endnotes, we can fake it with `::before` pseudo element. This would then eliminate having to provide a confusing 'Endnotes' header in the [new docs page template](https://docs.textpattern.com/brand/user-docs-page-template). Instead, the faux header appears automatically, but only if any Kramdown notes exist. A win-win. And yes, back matter of published material should be headed, even web documents, because it's _not_ footnotes!

Easy-peasy. Again, tweak to need, but I was just going by what I already saw in the styles...

```css
.footnotes::before {
    content: 'Endnotes'; /*DO NOT USE 'Footnotes', for Crom's sake!*/
    display: block;
    font-family: 'pt serif',georgia,serif;
    margin-bottom: 1em;
    font-size: 1.375rem; /*h3 size looks nice*/
}
```
If you're wondering about the comment there, see the the lengthy endnote on the guidelines page ranting about the misnomer that is 'footnotes'. Likely to be removed in the soon-ish future; immediately, if you add this item. ;)

And here are four selector requests for styling specific types of block-level content...

### Example blocks for none regular text DONE

Long story short, [block quotes](https://docs.textpattern.com/brand/user-docs-guide#block-quotes) are not appropriate for offsetting examples from regular text, but we don’t have any options. Thus, these two [example blocks](https://docs.textpattern.com/brand/user-docs-guide#example-blocks) selectors will go a long way, I suspect; especially the first one. At least they will for brand-oriented docs (procedures, guidelines, etc) where text examples are needed a lot.

* `.example-text`, See [Example text](https://docs.textpattern.com/brand/user-docs-guide#example-text)
* `.example-list`, See [Example list](https://docs.textpattern.com/brand/user-docs-guide#example-list)

The selector rules are combined in here:

```css
.example-text,
.example-list {
	margin-left:3%;
	border-left:3px dotted #c3edfa;
	padding-left:.5em;
}

.example-list {
	list-style-position:inside;
	list-style-type:'- ';
}
```

### File tree and directory lists DONE

This addresses a problem where people are using regular `code` to mark up lists that represent file trees, or components of them. That's missing a beat. So these two selectors give better visual distinction and semantic relevance. The ‘list-style-type’ for ‘.list-tree’ mimics parent child relations. That’s the idea, anyway.

- `.list-tree`, See [Full tree scope](https://docs.textpattern.com/brand/user-docs-guide#full-tree-scope)
- `.list-directory`, See [Single directory contents scope](https://docs.textpattern.com/brand/user-docs-guide#single-directory-contents-scope) 

The two are combined here:

```css
.list-tree {list-style-type:'☐ ';}
.list-tree ul, .list-tree ol {list-style-type:'└ ';}
.list-directory {list-style-type:'- ';}

.list-tree, .list-tree ul, .list-tree ol,
.list-directory {list-style-position:outside;}

.list-tree, .list-tree ul, .list-tree ol,
.list-directory {
	font-family:monospace; /*to make the code-happy people happy*/
	font-size:.7rem;
	line-height:1.1;
}

.list-tree li,
.list-directory li {
	margin-top:4px;
	margin-bottom:4px;
	margin-left:1.5em;
	margin-right:0;
}
```
That's all for now. Editor out. ;)
